# =============================================================================
# File: ANTA-IDS/ids/alerts.py
# Project: Advanced Network Traffic Analyzer & Intrusion Detection System
# Author: Golsar Abhishek
# Description:
#     IDS alert representation, storage, logging, querying, and presentation.
# =============================================================================

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from threading import RLock
from typing import Final

from config import (
    SHOW_SECURITY_ALERTS,
    VALID_SEVERITIES,
)
from utils.logger import Logger


logger = Logger.get_logger(__name__)


# =============================================================================
# Alert Configuration
# =============================================================================

DEFAULT_SEVERITY: Final[str] = "MEDIUM"

ALERT_SEPARATOR_WIDTH: Final[int] = 80


# =============================================================================
# Alert Model
# =============================================================================


@dataclass(frozen=True, slots=True)
class Alert:
    """
    Represents a single security alert generated by ANTA-IDS.

    Attributes
    ----------
    timestamp:
        Human-readable time at which the alert was generated.

    severity:
        Alert severity such as LOW, MEDIUM, HIGH, or CRITICAL.

    detector:
        Name of the IDS detector that generated the alert.

    source_ip:
        Source IP address associated with the event.

    destination_ip:
        Destination IP address associated with the event.

    message:
        Human-readable description of the detected activity.
    """

    timestamp: str
    severity: str
    detector: str
    source_ip: str
    destination_ip: str
    message: str

    def __str__(self) -> str:
        """
        Return a concise human-readable representation.
        """

        return (
            f"[{self.timestamp}] "
            f"[{self.severity}] "
            f"{self.detector} | "
            f"{self.source_ip} -> {self.destination_ip} | "
            f"{self.message}"
        )

    def __repr__(self) -> str:
        return (
            "Alert("
            f"timestamp={self.timestamp!r}, "
            f"severity={self.severity!r}, "
            f"detector={self.detector!r}, "
            f"source_ip={self.source_ip!r}, "
            f"destination_ip={self.destination_ip!r}"
            ")"
        )


# =============================================================================
# Alert Manager
# =============================================================================


class AlertManager:
    """
    Manage IDS alerts generated during the current ANTA-IDS session.

    Responsibilities
    ----------------
    - Create alerts
    - Validate alert fields
    - Store alerts
    - Log alerts
    - Display alerts
    - Query alerts
    - Clear alert history

    The manager uses a re-entrant lock so alert storage remains safe if packet
    processing becomes multi-threaded later.
    """

    def __init__(self) -> None:
        self._alerts: list[Alert] = []
        self._lock = RLock()

    # =========================================================================
    # Internal Helpers
    # =========================================================================

    @staticmethod
    def _normalize_severity(severity: str) -> str:
        """
        Normalize and validate an alert severity.

        Unknown or empty severities fall back to DEFAULT_SEVERITY.
        """

        normalized = str(severity).strip().upper()

        if not normalized:
            return DEFAULT_SEVERITY

        if normalized not in VALID_SEVERITIES:
            logger.warning(
                "Unknown IDS alert severity '%s'. "
                "Using '%s' instead.",
                normalized,
                DEFAULT_SEVERITY,
            )

            return DEFAULT_SEVERITY

        return normalized

    @staticmethod
    def _normalize_text(
        value: object,
        fallback: str = "-",
    ) -> str:
        """
        Convert an alert field into safe display text.
        """

        if value is None:
            return fallback

        text = str(value).strip()

        return text if text else fallback

    @staticmethod
    def _current_timestamp() -> str:
        """
        Return the current local time used by console alerts.
        """

        return datetime.now().strftime("%H:%M:%S")

    # =========================================================================
    # Create Alert
    # =========================================================================

    def add_alert(
        self,
        severity: str,
        detector: str,
        source_ip: str,
        destination_ip: str,
        message: str,
    ) -> Alert:
        """
        Create, store, log, and optionally display a new IDS alert.

        Parameters
        ----------
        severity:
            Alert severity.

        detector:
            Detector name.

        source_ip:
            Source IP associated with the event.

        destination_ip:
            Destination IP associated with the event.

        message:
            Description of the detected activity.

        Returns
        -------
        Alert
            Newly created alert.
        """

        alert = Alert(
            timestamp=self._current_timestamp(),
            severity=self._normalize_severity(severity),
            detector=self._normalize_text(
                detector,
                "Unknown Detector",
            ),
            source_ip=self._normalize_text(source_ip),
            destination_ip=self._normalize_text(destination_ip),
            message=self._normalize_text(
                message,
                "No description available.",
            ),
        )

        with self._lock:
            self._alerts.append(alert)

        self._log_alert(alert)

        if SHOW_SECURITY_ALERTS:
            self.show_alert(alert)

        return alert

    # =========================================================================
    # Logging
    # =========================================================================

    @staticmethod
    def _log_alert(alert: Alert) -> None:
        """
        Write an alert to the ANTA-IDS logging system.

        Higher-severity events use higher logging levels where appropriate.
        """

        log_message = (
            "IDS ALERT | %s | %s | %s -> %s | %s"
        )

        log_args = (
            alert.severity,
            alert.detector,
            alert.source_ip,
            alert.destination_ip,
            alert.message,
        )

        if alert.severity == "CRITICAL":
            logger.critical(
                log_message,
                *log_args,
            )

        elif alert.severity in {"HIGH", "MEDIUM"}:
            logger.warning(
                log_message,
                *log_args,
            )

        else:
            logger.info(
                log_message,
                *log_args,
            )

    # =========================================================================
    # Display Alert
    # =========================================================================

    @staticmethod
    def show_alert(alert: Alert) -> None:
        """
        Display a formatted IDS alert in the console.
        """

        separator = "=" * ALERT_SEPARATOR_WIDTH

        print()
        print(separator)
        print("SECURITY ALERT")
        print(separator)

        print(f"Time        : {alert.timestamp}")
        print(f"Severity    : {alert.severity}")
        print(f"Detector    : {alert.detector}")
        print(f"Source IP   : {alert.source_ip}")
        print(f"Destination : {alert.destination_ip}")
        print(f"Description : {alert.message}")

        print(separator)
        print()

    # =========================================================================
    # Accessors
    # =========================================================================

    def get_alerts(self) -> list[Alert]:
        """
        Return a copy of all generated alerts.

        Returning a copy prevents callers from modifying the manager's
        internal alert list.
        """

        with self._lock:
            return list(self._alerts)

    def get_latest_alert(self) -> Alert | None:
        """
        Return the most recently generated alert.

        Returns None when no alerts have been generated.
        """

        with self._lock:
            if not self._alerts:
                return None

            return self._alerts[-1]

    def alert_count(self) -> int:
        """
        Return the total number of generated alerts.
        """

        with self._lock:
            return len(self._alerts)

    # =========================================================================
    # Alert Queries
    # =========================================================================

    def get_by_severity(
        self,
        severity: str,
    ) -> list[Alert]:
        """
        Return alerts matching the requested severity.
        """

        normalized = str(severity).strip().upper()

        with self._lock:
            return [
                alert
                for alert in self._alerts
                if alert.severity == normalized
            ]

    def get_by_detector(
        self,
        detector: str,
    ) -> list[Alert]:
        """
        Return alerts generated by a specific detector.

        Matching is case-insensitive.
        """

        target = str(detector).strip().casefold()

        if not target:
            return []

        with self._lock:
            return [
                alert
                for alert in self._alerts
                if alert.detector.casefold() == target
            ]

    def get_by_source(
        self,
        source_ip: str,
    ) -> list[Alert]:
        """
        Return alerts associated with a specific source IP.
        """

        target = str(source_ip).strip()

        if not target:
            return []

        with self._lock:
            return [
                alert
                for alert in self._alerts
                if alert.source_ip == target
            ]

    def get_by_destination(
        self,
        destination_ip: str,
    ) -> list[Alert]:
        """
        Return alerts associated with a specific destination IP.
        """

        target = str(destination_ip).strip()

        if not target:
            return []

        with self._lock:
            return [
                alert
                for alert in self._alerts
                if alert.destination_ip == target
            ]

    # =========================================================================
    # Alert Statistics
    # =========================================================================

    def severity_counts(self) -> dict[str, int]:
        """
        Return the number of alerts generated for each severity.
        """

        counts: dict[str, int] = {}

        with self._lock:
            for alert in self._alerts:
                counts[alert.severity] = (
                    counts.get(alert.severity, 0) + 1
                )

        return counts

    def detector_counts(self) -> dict[str, int]:
        """
        Return the number of alerts generated by each detector.
        """

        counts: dict[str, int] = {}

        with self._lock:
            for alert in self._alerts:
                counts[alert.detector] = (
                    counts.get(alert.detector, 0) + 1
                )

        return counts

    # =========================================================================
    # Clear Alert History
    # =========================================================================

    def clear(self) -> None:
        """
        Remove all alerts stored in memory.
        """

        with self._lock:
            count = len(self._alerts)
            self._alerts.clear()

        if count:
            logger.info(
                "Cleared %d stored IDS alert(s).",
                count,
            )

    # =========================================================================
    # Python Helpers
    # =========================================================================

    def __len__(self) -> int:
        return self.alert_count()

    def __bool__(self) -> bool:
        return self.alert_count() > 0

    def __iter__(self):
        """
        Iterate over a snapshot of the current alerts.

        A snapshot avoids exposing the internal list while another thread
        potentially adds alerts.
        """

        return iter(self.get_alerts())

    def __repr__(self) -> str:
        return (
            f"AlertManager("
            f"alerts={self.alert_count()}"
            f")"
        )