"""
===============================================================================
ANTA-IDS
Advanced Network Traffic Analyzer & Intrusion Detection System

File:
    main.py

Description:
    Main application entry point responsible for initializing ANTA-IDS,
    selecting the capture interface, starting packet capture, and routing
    packets through the analysis and IDS pipeline.
===============================================================================
"""

from __future__ import annotations

import time
from typing import Any

from analyzer.flow import FlowManager
from analyzer.protocol import ProtocolAnalyzer
from analyzer.statistics import StatisticsManager
from capture.interfaces import InterfaceManager, NetworkInterface
from capture.parser import PacketParser
from capture.sniffer import PacketSniffer
from gui.console import ConsoleDisplay
from ids.detector import IDSDetector
from utils.logger import Logger


logger = Logger.get_logger(__name__)


# =============================================================================
# Application Configuration
# =============================================================================

# Delay used by the main thread while AsyncSniffer performs capture in the
# background. This prevents unnecessary CPU usage.
MAIN_LOOP_SLEEP = 0.1

# Display live statistics after this many processed packets.
STATISTICS_INTERVAL = 50


# =============================================================================
# Development / Debug Configuration
# =============================================================================

# Enable only while debugging packets generated by the Kali test machine.
DEBUG_KALI_TRAFFIC = False

# Development/testing machine.
KALI_IP = "10.23.81.115"


# =============================================================================
# Module Initialization
# =============================================================================


def initialize_modules() -> tuple[
    InterfaceManager,
    PacketParser,
    FlowManager,
    StatisticsManager,
    ProtocolAnalyzer,
    IDSDetector,
    ConsoleDisplay,
]:
    """
    Initialize all ANTA-IDS application modules.

    Returns
    -------
    tuple
        Initialized ANTA-IDS components.
    """

    interface_manager = InterfaceManager()
    parser = PacketParser()
    flow_manager = FlowManager()
    statistics = StatisticsManager()
    protocol_analyzer = ProtocolAnalyzer()
    detector = IDSDetector()
    display = ConsoleDisplay()

    return (
        interface_manager,
        parser,
        flow_manager,
        statistics,
        protocol_analyzer,
        detector,
        display,
    )


# =============================================================================
# Interface Selection
# =============================================================================


def select_interface(
    interface_manager: InterfaceManager,
) -> NetworkInterface | None:
    """
    Display available interfaces and allow the user to select one.

    Returns
    -------
    NetworkInterface | None
        Selected interface, or None if selection was cancelled.
    """

    interface_manager.display_interfaces()

    while True:
        try:
            raw_choice = input("\nSelect Interface: ").strip()

            if not raw_choice:
                print("Please enter an interface number.")
                continue

            choice = int(raw_choice)

            selected_interface = interface_manager.get_interface(choice)

            if selected_interface is None:
                print("Invalid selection. Please try again.")
                continue

            return selected_interface

        except ValueError:
            print("Please enter a valid interface number.")

        except (KeyboardInterrupt, EOFError):
            print("\nInterface selection cancelled.")
            return None


# =============================================================================
# Debug Output
# =============================================================================


def show_debug_packet(packet_info: Any) -> None:
    """
    Display development/debug information for traffic generated by the
    configured Kali test machine.
    """

    if not DEBUG_KALI_TRAFFIC:
        return

    src_ip = getattr(packet_info, "src_ip", "")
    if src_ip != KALI_IP:
        return

    protocol = getattr(packet_info, "protocol", "-")
    src_port = getattr(packet_info, "src_port", None)
    dst_ip = getattr(packet_info, "dst_ip", "-")
    dst_port = getattr(packet_info, "dst_port", None)
    tcp_flags = getattr(packet_info, "tcp_flags", None)

    src_endpoint = (
        f"{src_ip}:{src_port}"
        if src_port is not None
        else src_ip
    )

    dst_endpoint = (
        f"{dst_ip}:{dst_port}"
        if dst_port is not None
        else dst_ip
    )

    print(
        "\n[PIPELINE DEBUG] "
        f"{protocol} "
        f"{src_endpoint} -> {dst_endpoint} "
        f"flags={tcp_flags or '-'}"
    )


# =============================================================================
# Main Application
# =============================================================================


def main() -> None:
    """
    Start ANTA-IDS and process live network traffic.

    Packet pipeline:

        Raw Packet
            |
            v
        PacketParser
            |
            v
        FlowManager
            |
            v
        StatisticsManager
            |
            v
        ProtocolAnalyzer
            |
            v
        IDSDetector
            |
            v
        ConsoleDisplay
    """

    logger.info("=" * 60)
    logger.info("Starting ANTA-IDS")

    # =========================================================================
    # Initialize Modules
    # =========================================================================

    try:
        (
            interface_manager,
            parser,
            flow_manager,
            statistics,
            protocol_analyzer,
            detector,
            display,
        ) = initialize_modules()

    except Exception:
        logger.exception(
            "Failed to initialize ANTA-IDS modules."
        )

        print("\nFailed to initialize ANTA-IDS.")
        return

    logger.info(
        "All modules initialized successfully."
    )

    # =========================================================================
    # Select Capture Interface
    # =========================================================================

    try:
        selected_interface = select_interface(
            interface_manager
        )

    except Exception:
        logger.exception(
            "Unexpected error during interface selection."
        )

        print(
            "\nUnable to select network interface."
        )
        return

    if selected_interface is None:
        logger.info(
            "ANTA-IDS startup cancelled by user."
        )
        return

    scapy_interface = (
        selected_interface.scapy_name
        or selected_interface.name
    )

    print(
        f"\nSelected Interface : "
        f"{selected_interface.name}"
    )

    if selected_interface.ipv4:
        print(
            f"IPv4 Address       : "
            f"{selected_interface.ipv4}"
        )

    print()

    logger.info(
        "Selected capture interface: %s",
        selected_interface.name,
    )

    logger.info(
        "Scapy capture interface: %s",
        scapy_interface,
    )

    # =========================================================================
    # Console Banner
    # =========================================================================

    display.show_banner()

    print("\nListening for network traffic...")
    print("Press Ctrl+C to stop.\n")

    # =========================================================================
    # Packet Callback
    # =========================================================================

    def packet_callback(packet: Any) -> None:
        """
        Process one raw packet through the complete ANTA-IDS pipeline.

        A packet-processing failure is isolated to the affected packet so that
        live capture can continue.
        """

        try:
            # -----------------------------------------------------------------
            # 1. Packet Parsing
            # -----------------------------------------------------------------

            packet_info = parser.parse(packet)

            if packet_info is None:
                return

            # -----------------------------------------------------------------
            # 2. Development Debugging
            # -----------------------------------------------------------------

            show_debug_packet(packet_info)

            # -----------------------------------------------------------------
            # 3. Flow Tracking
            # -----------------------------------------------------------------

            flow_manager.add_packet(packet_info)

            # -----------------------------------------------------------------
            # 4. Statistics
            # -----------------------------------------------------------------

            statistics.update(packet_info)

            # -----------------------------------------------------------------
            # 5. Protocol Analysis
            # -----------------------------------------------------------------

            analysis = protocol_analyzer.analyze(
                packet_info
            )

            # -----------------------------------------------------------------
            # 6. Intrusion Detection
            # -----------------------------------------------------------------

            detector.analyze(packet_info)

            # -----------------------------------------------------------------
            # 7. Console Packet Display
            # -----------------------------------------------------------------

            display.show_packet(
                packet_info,
                analysis,
            )

            # -----------------------------------------------------------------
            # 8. Periodic Statistics
            # -----------------------------------------------------------------

            packet_count = statistics.packet_count()

            if (
                packet_count > 0
                and packet_count % STATISTICS_INTERVAL == 0
            ):
                display.show_statistics(
                    statistics
                )

        except Exception:
            logger.exception(
                "Packet processing failed."
            )

    # =========================================================================
    # Initialize Packet Sniffer
    # =========================================================================

    try:
        sniffer = PacketSniffer(
            interface=selected_interface,
            packet_callback=packet_callback,
        )

    except Exception:
        logger.exception(
            "Failed to initialize PacketSniffer."
        )

        print(
            "\nFailed to initialize packet capture."
        )
        return

    # =========================================================================
    # Start Packet Capture
    # =========================================================================

    try:
        capture_started = sniffer.start()

        if not capture_started:
            logger.error(
                "Failed to start packet capture."
            )

            print(
                "\nFailed to start packet capture."
            )
            return

        # AsyncSniffer performs capture in its own thread.
        # The main thread only needs to remain alive.
        while sniffer.is_running:
            time.sleep(MAIN_LOOP_SLEEP)

    except KeyboardInterrupt:
        print("\nStopping packet capture...")

        logger.info(
            "Capture interrupted by user."
        )

    except Exception:
        logger.exception(
            "Unexpected ANTA-IDS application error."
        )

        print(
            "\nUnexpected ANTA-IDS application error."
        )

    finally:
        try:
            sniffer.stop()

        except Exception:
            logger.exception(
                "Error during packet sniffer shutdown."
            )

        logger.info("ANTA-IDS stopped.")

        print(
            "Capture stopped successfully."
        )


# =============================================================================
# Entry Point
# =============================================================================


if __name__ == "__main__":
    main()